version: '3'                                                                                                                          
services:
  confluence:
    image: atlassian/confluence-server:7.6.1
    volumes:
      -  /app/atlassian/application-data/confluence:/var/atlassian/application-data/confluence
    container_name: confluence
    ports:
      - "8090:8090"
      - "8091:8091"
    environment:
      - CATALINA_CONNECTOR_PROXYNAME="{sub.domain.com}"
      - CATALINA_CONNECTOR_PROXYPORT=443
      - CATALINA_CONNECTOR_SCHEME=https
      - CATALINA_CONNECTOR_SECURE=true
