version: '3' 
services:
  postgres:
    image: postgres:10.13
    command: 
      - "postgres"
      - "-c"
      - "max_connections=200"
      - "-c"
      - "shared_buffers=4GB"
      - "-c"
      - "wal_buffers=128MB"
    volumes:
      - /app/postgresql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD={password}
    container_name: postgresql
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    container_name: pg_admin4
    environment:
      - PGADMIN_DEFAULT_EMAIL={email@example.com}
      - PGADMIN_DEFAULT_PASSWORD={password}
    ports:
      - "5555:80"
    volumes:
      - /app/pgadmin4/data:/var/lib/pgadmin
