version: '3.1'
services:
  db:
    image: mariadb:10.5.8
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: {password}
    ports:
      - 3306:3306
    volumes:
      - /app/mariadb/data:/var/lib/mysql
